server:
  port: 20000
spring:
  servlet:
    multipart:
      max-file-size: 200MB
      max-request-size: 200MB
  http:
    encoding:
      force: true
      charset: UTF-8
  mvc:
    throw-exception-if-no-handler-found: true
  resources:
    add-mappings: false
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://数据库服务器地址:3306/MyOssDB?useUnicode=true&characterEncoding=utf8&characterSetResults=utf8&useSSL=false&serverTimezone=GMT%2b8
    username: 用户
    password: 密码
mybatis:
  config-location: classpath:mybatis-config.xml